---
- name: Converge
  hosts: containerd
  become: true
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        cache_valid_time: 600
        update_cache: true

  roles:
    - role: pako.containerd
